mutation CreateCarPool($data: CarPoolerInput!) {
  createCarPool(data: $data) {
    id
    departureDateTime
    passengerNumber
    passengerId
    driverId
    departureCity {
      cityName
    }
    arrivalCity {
      cityName
    }
  }
}
query GetCarPool($getCarPoolId: Int!) {
  getCarPool(id: $getCarPoolId) {
    departureCity {
      cityName
    }
    arrivalCity {
      cityName
    }
    departureDateTime
    passengerNumber
    passengerId
    driverId
  }
}
query Query {
  getCarPools {
    id
    departureCity {
      cityName
    }
    arrivalCity {
      cityName
    }
    departureDateTime
    passengerNumber
    driverId
  }
}
# mutation UpdateCarpool(
#   $data: CarPoolerInput!
#   $carPoolId: Int!
#   $userId: Int!
# ) {
#   updateCarpool(data: $data, carPoolId: $carPoolId, userId: $userId) {
#     id
#     departureCity
#     arrivalCity
#     departureDateTime
#     passengerNumber
#     passengerId
#     driverId
#   }
# }
mutation DeleteCarPool($deleteCarPoolId: Int!) {
  deleteCarPool(id: $deleteCarPoolId)
}
query GetCarPoolByCities($data: getCarPoolByCitiesInput!) {
  getCarPoolByCities(data: $data) {
    departureCity {
      cityName
    }
    arrivalCity {
      cityName
    }
    departureDateTime
    passengerNumber
    passengerId
    driverId
    id
  }
}
