query getProfile {
  profile {
    id
    email
    profilePicture
    profileDescription
    firstName
    lastName
    role
  }
}
mutation updateUser($data: UserInput!, $updateUserId: Int!) {
  updateUser(data: $data, id: $updateUserId) {
    id
    email
    profilePicture
    profileDescription
    firstName
    lastName
    role
  }
}
