query getProfile {
  profile {
    id
    email
    profilePicture
    profileDescription
    firstName
    lastName
    role
    age
  }
}
mutation UpdateUser($data: UserUpdateInput!) {
  updateUser(data: $data) {
    id
    email
    profilePicture
    profileDescription
    firstName
    lastName
    role
    age
    expoNotificationsToken
  }
}
