name: integration-tests

on: pull_request

jobs:
  test-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_JWT_PRIVATE_KEY: zeyfgzeigfyzegfyuzegf
          envkey_NODE_ENV: "development"
          envkey_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:4000"
          envkey_SERVER_HOST: "localhost"
          envkey_SERVER_PORT: "4000"
          envkey_DB_HOST: localhost
          envkey_DB_USER: postgres
          envkey_DB_PASS: postgres
          envkey_DB_NAME: postgres
          envkey_DB_PORT: 5432
          envkey_HereApiKey: P_cC9-TJ-odVVXPLOOyabwU7n7TqMvCpLWlMIbGWep0
          directory: server
          file_name: .env
      - name: Run integration test
        run: npm run integration-tests
